const guestList = [
  'Mr. Russell Geltman & Guest',
  'Mr. and Mrs. Jeremy Geltman & Family',
  'Mr. and Mrs. Lionel Geltman',
  'Mr. and Mrs. Matt Greco',
  'Mr. and Mrs. Gary Lipson',
  "Mr. Sam Lipson and Ms. Erica O'Connell",
  'Mr. Mark Solomon and Ms. Maryann Edwards',
  'Mr. and Mrs. Jason Solomon & Family',
  'Mr. and Mrs. Alan Geltman & Family',
  'Mr. Ian Geltman',
  'Mr. and Mrs. Jim Vazquez & Family ',
  'Mr. and Mrs. JD Kluxen & Family',
  'Mr. Adam Osowsky',
  'Mr. and Mrs. Irving Osowsky',
  'Mr. and Mrs. Rodney Roig',
  'Mr. and Mrs. Howard Katz',
  'Mr. and Mrs. Fred Pfister & Family',
  'Dr. and Mrs. Daniel Roig',
  'Ms. Jessica Roig',
  'Mr. and Mrs. Chris Christison',
  'Mr. Richard Klurstein',
  'Mr. and Mrs. Bruce Bader',
  'Ms. Melanie Bader',
  'Mr. Matthew Bader',
  'Ms. Carole Berliner and Mr. Marshall Lacoff',
  'Mr. Benjamin Berliner and Ms. Jennifer Ingram',
  'Mr. Robert Berliner and Ms. Carrie Boland',
  'Mr. and Mrs. Robert Bader & Family',
  'Mr. and Mrs. Michael Bader',
  'Mrs. Ilene Klurstein',
  'Mr. and Mrs. Robert Bouman & Family',
  'Mr. and Mrs. Greg Fisher & Family',
  'Mr. and Mrs. Marty Dretel',
  'Mrs. Barbara Moglia',
  'Mr. and Mrs. Kenneth Wolk',
  'Mr. and Mrs. Herbert Wolk',
  'Dr. and Mrs. Melvin Wolk',
  'Ms. Judith Ogens',
  'Mr. and Mrs. Daniel Cohen',
  'Mr. and Mrs. David Ogens',
  'Mr. Samuel Cohen and Ms. Bobbi',
  'Mr. and Mrs. Arthur Silverstone',
  'Mr. and Mrs. Mark Maluso',
  'Mr. and Mrs. Joseph Silverstone',
  'Ms. Arlene Lenchus and Guest',
  'Mr. and Mrs. Douglas Heller',
  'Mr. and Mrs. William Chapman',
  'Mr. and Mrs. Blanchard Hiatt',
  'Mr. and Mrs. Gerald Goldberg',
  'Dr. Paul Heller and Guest',
  'Mr. and Mrs. Stuart Bauer',
  'Mrs. Maddy Sinoway',
  'Dr. Ken Kline and Mrs. Jordana Zeger',
  'Rabbi and Mrs. Joel Soffin',
  'Mr. and Mrs. Arthur Schwartz',
  'Mrs. Renee Lipson',
  'Ms. Karyn Martel',
  'Mrs. Robin Vrba',
  'Mr. and Mrs. Richard Rosen',
  'Dr. and Mrs. Howard Goodkin',
  'Dr. and Mrs. Jack Goldshlack',
  'Mr. and Mrs. Daniel Goldshlack',
  'Mr. and Mrs. Paul Bornstein',
  'Mr. and Mrs. Thomas Greco',
  'Ms. Danielle Malmgren & Guest ',
  'Ms. Isabelle Putnam & Mr. Reed Risner',
  'Ms. Jeannie Sabaroff & Guest',
  'Ms. Ashlyn Rogers & Guest',
  'Mr. And Mrs. Kevin Murray',
  'Mr. and Mrs. Alexander Odell',
  'Mr. Brian Streem & Guest ',
  'Mr. Jackie Joe Michael Luke Hancock and Ms. Aline Ramirez Barta',
  'Ms. Olivia Paden & Mr. Loren Klick',
  'Ms. Marika Nakamura & Mr. Hugo Romano',
  'Ms. Shanna Miller & Guest',
  'Ms. Marianne Deschaine and Mr. Thomas Marshall',
  'Ms. Marianna Silchuk & Guest',
  'Mr. and Mrs. Sean Layton',
  'Mr. and Mrs. Max Holvik',
  'Ms. Caitlyn Carminati and Mr. John Kuhns',
  'Mr. and Mrs. Daniel Mottoh',
  'Ms. Ro Rabanilla and Mr. Thomas Kent',
  'Ms. Liz Kelly and Mr. David Schwartz',
  'Ms. Ani Madueno and Mr. Marco Rivenz',
  'Mr. and Mrs. John Malmgren',
  'Mr. and Mrs. Paul Malmgren',
  'Ms. Loretta Malmgren and Mr. Bryant Malmgren',
  'Mr. Jeffrey Malmgren',
  'Mr. and Mrs. Jason Lee',
  'Ms. Brooke Miller and Guest',
  'Mr. Sean Miller and Ms. Hannah Shepherd',
  'Mr. and Mrs. Chad Miller',
  'Mr. and Mrs. Ian Anderson',
  'Mr. and Mrs. Marty Petersen',
  'Mr. and Mrs. Tom Molenda',
  'Mr. and Mrs. Dan Miller',
  'Mr. and Mrs. Houlberg',
  'Ms. Alexis Freitag & Guest',
  'Mr. & Mrs. Tommy Joe Conway',
  'Mrs. & Mrs. Lilyana Gonzales Hudson',
  'Ms. Chou Ha Ma & Guest',
  'Mr. & Mrs. Alan Cano',
  'Mr. and Mrs. Andrew Kukta',
  'Mr. & Mrs. Jimmy Rose',
  'Mr. and Mrs. James Villa ',
  'Mr. and Mrs. Tom Wedlick',
  'Mr. and Mrs. James Kozlowski',
  'Drs. Daniel and Janine Heller ',
  'Mr. and Mrs. Myron Solomon',
  'Mr. and Mrs. Leonard Loew',
  'Mrs. Cathy Matulowitz',
  'Mr. and Mrs. Ray Ayotte',
  'Mr. and Mrs. Sam Klein',
  'Mr. and Mrs. Chris Klose',
  'Mr. and Mrs. Alex Kerschhofer',
  'Mr. Michael Gould and Ms. Sandra Badillo ',
  'Ms. Jeanmarie Murphy',
  'Mr. and Mrs. Reid Caraher',
  'Mr. Steven Luna',
  'Ms. Brooke Briseno',
  'Mr. and Mrs. Emre Erdogan',
  'Mr. and Mrs. Michael Breard',
  'Mrs. & Mr. Roxane Willard Koborsi',
  'Mr. Benjamin Yaxley and Ms. Carolina Cala',
  'Mr. and Mrs. Ross Solomon',
  'Ms. Meghan Hoopes and Guest',
  'Ms. Marisa Bouman and Mr. Tyler Burdorf'
];

export default guestList;
